version : "3"
services:
  devc-api:
    build:
      context: .
      dockerfile: dockerfiles/Ci.Dockerfile
    container_name: devc-api
    depends_on:
      - devc-pg
    restart: always
    ports:
      - "23102:80"
    environment:
      APP_NAME: "Laravel API boilerplate"
      DB_HOST: "devc-pg"
      MAIL_HOST: "devc-mailpit"
    networks:
      devc-network:
        ipv4_address: 23.102.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  devc-pg:
    image: postgres:15
    container_name: devc-pg
    volumes:
      - devc-pg-disk:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    networks:
      devc-network:
        ipv4_address: 23.102.1.2

  devc-mailpit:
    image: 'axllent/mailpit:latest'
    container_name: devc-mailpit
    restart: always
    networks:
      devc-network:
        ipv4_address: 23.102.1.3

#  devc-q:
#    build:
#      context: .
#      dockerfile: dockerfiles/QueueListener.Dockerfile
#    container_name: devc-q
#    depends_on:
#      - devc-api
#    volumes:
#      - .:/var/www/html
#    restart: unless-stopped
#    networks:
#      devc-network:
#        ipv4_address: 23.102.1.4

#  devc-0x:
#    build:
#      context: .
#      dockerfile: dockerfiles/0x.Dockerfile
#    container_name: devc-0x
#    depends_on:
#      - devc-api
#    volumes:
#      - .:/var/www/html
#    restart: always
#    networks:
#      devc-network:
#        ipv4_address: 23.102.1.5

#  devc-fe-app:
#    build:
#      context: .
#      dockerfile: dockerfiles/FeApp.Dockerfile
#    container_name: devc-fe-app
#    ports:
#      - "1001:3000"
#    volumes:
#      - ./fe-app:/var/www/html
#      #- ./dockerfiles:/var/www/html/dockerfiles
#    restart: always
#    networks:
#      devc-network:
#        ipv4_address: 23.102.1.6

# On-disk storage of DB data, when containers are stopped
volumes:
  devc-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  devc-network:
    ipam:
      driver: default
      config:
        - subnet: 23.102.0.0/16
